version: '3'
services:
  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile.flask
    command: bash -c "python run.py"
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000