FROM python:3.11-buster

WORKDIR /usr/src/app
COPY . .

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt