FROM node:17.2.0-buster

WORKDIR /app

COPY ./vue .
RUN npm install

# 安裝常用工具和依賴
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        build-essential \
        curl \
        nmap \
        git \
        nano \
    && rm -rf /var/lib/apt/lists/*

# 全局安裝 Vue CLI
RUN npm install -g @vue/cli@4.5.15